### ISSUE TITLE
Enchantment books can't be applied to items in the anvil.

### ISSUE THREAD

**Issue by mxruben** [SteelCodeTeam/StuffAintCheap#1]
Enchantment books from villages contain the wrong nbt tag. They have the "Enchantments" tag instead of the "StoredEnchantments" tag that normal books have.

**Comment by SteelCodeTeam** [comment]
Thank you soo much for your pull request and for taking an interest in the mod!

We accept it and implement the same changes in version 1.19.2

All the best!
